services:
  - type: web
    name: cctv-business
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT